galaxy_info:
  author: Daniel Higginbotham
  description: Sets up common vars for other clojure-uberjar-webapp roles
  company: http://www.braveclojure.com/
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - clojure
    - web
dependencies: []
